export const invoiceFormData = [
  {
      label: " Customer Name",
      name: "customerName",
      componentType: "input",
      type: "text",
      placeholder: "Enter Customer Name",
    },
  {
      label: "Product",
      name: "product",
      componentType: "input",
      type: "text",
      placeholder: "Enter Product Name",
    },
    {
      label: "Brand Name",
      name: "brandName",
      componentType: "input",
      type: "text",
      placeholder: "Enter Brand Name",
    },
    {
      label: "Quantity",
      name: "quantity",
      componentType: "input",
      type: "number",
      placeholder: "Enter product quantity",
    },
    {
      label: "Unit Price",
      name: "unitPrice",
      componentType: "input",
      type: "number",
      placeholder: "Enter Unit Price",
    },
  
  
]



export const invoiceFormDetailsData = [
  {
      label: " Company Name",
      name: "companyName",
      componentType: "input",
      type: "text",
      placeholder: "Enter Customer Name",
    },
  {
      label: "Address",
      name: "address",
      componentType: "input",
      type: "text",
      placeholder: "Enter Address Name",
    },
  
]

export const initialData = [
{
  index: 0,
  id: "101",
  invoice_no: "202501-62",
  cashier: "Daugherty Freeman",
  customer: "Lena Dickerson",
  address: "629 Gates Avenue, Manila, Ohio, 2336",
  company: "XLEEN",
  email: "lenadickerson@xleen.com",
  phone: "+880 (946) 431-3573",
  trans_date: "2021-10-08",
  due_date: "2023-05-11",
},
{
  index: 1,
  id: "102",
  invoice_no: "202501-55",
  cashier: "Robinson Mooney",
  customer: "Copeland Sparks",
  address: "503 Polar Street, Kanauga, Massachusetts, 3984",
  company: "TERRAGEN",
  email: "copelandsparks@terragen.com",
  phone: "+880 (983) 405-2774",
  trans_date: "2020-12-06",
  due_date: "2022-11-27",
},
{
  index: 2,
  id: "103",
  invoice_no: "202501-77",
  cashier: "Lori Leonard",
  customer: "Farley Wise",
  address: "492 Montauk Avenue, Sterling, Washington, 1063",
  company: "JUNIPOOR",
  email: "farleywise@junipoor.com",
  phone: "+880 (812) 530-3166",
  trans_date: "2022-12-22",
  due_date: "2021-03-11",
},
{
  index: 0,
  id: "104",
  invoice_no: "202501-81",
  cashier: "Mason Hart",
  customer: "Vivian Hayes",
  address: "786 Sunset Boulevard, Doral, Florida, 33178",
  company: "PROGENEX",
  email: "vivianhayes@progenex.com",
  phone: "+880 (912) 500-6543",
  trans_date: "2023-04-14",
  due_date: "2025-01-10",
},
{
  index: 1,
  id: "105",
  invoice_no: "202501-72",
  cashier: "Sophia Morgan",
  customer: "Dean Lambert",
  address: "432 Elm Street, Boulder, Colorado, 80302",
  company: "INFINIQ",
  email: "deanlambert@infiniq.com",
  phone: "+880 (812) 401-8743",
  trans_date: "2022-03-18",
  due_date: "2023-11-22",
},
{
  index: 2,
  id: "106",
  invoice_no: "202501-64",
  cashier: "Ava James",
  customer: "Rosie Harper",
  address: "950 Main Street, Austin, Texas, 73301",
  company: "OVERTURE",
  email: "rosieharper@overture.com",
  phone: "+880 (921) 372-3492",
  trans_date: "2021-07-19",
  due_date: "2024-03-15",
},
{
  index: 3,
  id: "107",
  invoice_no: "202501-99",
  cashier: "Ethan Mitchell",
  customer: "Bryan Fox",
  address: "154 North Avenue, Salem, Oregon, 97301",
  company: "ZENCORE",
  email: "bryanfox@zencore.com",
  phone: "+880 (832) 458-2136",
  trans_date: "2020-11-05",
  due_date: "2023-06-30",
},
{
  index: 4,
  id: "108",
  invoice_no: "202501-88",
  cashier: "Olivia Perry",
  customer: "Hazel Rivera",
  address: "67 Cherry Lane, Dover, Delaware, 19901",
  company: "BLUEMATRIX",
  email: "hazelrivera@bluematrix.com",
  phone: "+880 (893) 573-1247",
  trans_date: "2023-01-09",
  due_date: "2025-04-18",
},
{
  index: 5,
  id: "109",
  invoice_no: "202501-53",
  cashier: "Lucas Walker",
  customer: "Frankie Newman",
  address: "23 Hill Street, Omaha, Nebraska, 68102",
  company: "NEXTSYNC",
  email: "frankienewman@nextsync.com",
  phone: "+880 (981) 425-6598",
  trans_date: "2022-09-12",
  due_date: "2024-08-25",
},
{
  index: 6,
  id: "110",
  invoice_no: "202501-45",
  cashier: "Emily Scott",
  customer: "Gavin Carter",
  address: "378 Olive Road, Orlando, Florida, 32801",
  company: "OPTIMAX",
  email: "gavincarter@optimax.com",
  phone: "+880 (873) 342-5982",
  trans_date: "2021-06-11",
  due_date: "2023-10-05",
},
{
  index: 7,
  id: "111",
  invoice_no: "202501-66",
  cashier: "Daniel Brown",
  customer: "Natalie Cooper",
  address: "759 Oak Drive, Springfield, Illinois, 62704",
  company: "ELEVATRIX",
  email: "nataliecooper@elevatrix.com",
  phone: "+880 (893) 651-7831",
  trans_date: "2020-08-08",
  due_date: "2024-02-14",
},
{
  index: 8,
  id: "112",
  invoice_no: "202501-92",
  cashier: "Amelia Green",
  customer: "Peyton Ward",
  address: "244 Cedar Avenue, Phoenix, Arizona, 85001",
  company: "CIRCUITPLUS",
  email: "peytonward@circuitplus.com",
  phone: "+880 (923) 572-1945",
  trans_date: "2023-03-05",
  due_date: "2025-07-22",
},
{
  index: 9,
  id: "113",
  invoice_no: "202501-79",
  cashier: "Henry Thompson",
  customer: "Lila Foster",
  address: "510 Pine Street, Seattle, Washington, 98101",
  company: "HORIZONTECH",
  email: "lilafoster@horizontech.com",
  phone: "+880 (984) 611-2954",
  trans_date: "2021-02-20",
  due_date: "2023-12-01",
},
];



export const headerColumns = [
{ Header: 'ID', accessor: 'id' },
{ Header: 'Name', accessor: 'customer' },
{ Header: 'Email', accessor: 'email' },
{ Header: 'Phone', accessor: 'phone' },
{ Header: 'Company', accessor: 'company' },
{ Header: 'Product', accessor: 'product' },
{ Header: 'Quantity', accessor: 'quantity' },
{ Header: 'Address', accessor: 'address' },
{ Header: 'Invoice', accessor: 'invoice_no' },
{ Header: 'Tax Rate', accessor: 'taxRate' },
{ Header: 'Discount Rate', accessor: 'discountRate' },
{ Header: 'Subtotal', accessor: 'subtotal' },
{ Header: 'Total', accessor: 'total' },
];

export const products = [
  { "index": 1, "id": "laptop", "product": "Asus TUF Gaming A15" },
  { "index": 2, "id": "phone", "product": "iPhone 16 Pro" },
  { "index": 3, "id": "tablet", "product": "Samsung Galaxy Tab S8" },
  { "index": 4, "id": "smartwatch", "product": "Apple Watch Series 8" },
  { "index": 5, "id": "keyboard", "product": "A4 Tech Keyboard" },
  { "index": 6, "id": "mouse", "product": "Logitech MX Master 3" },
  { "index": 7, "id": "monitor", "product": "Dell UltraSharp 27" },
  { "index": 8, "id": "headphones", "product": "Sony WH-1000XM5" },
  { "index": 9, "id": "speaker", "product": "JBL Charge 5" },
  { "index": 10, "id": "camera", "product": "Canon EOS R6" }
];
